In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("sales_data.csv")
## fecth the first 5 rows
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi’s 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [7]:
## fetch the last 5 rows
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
15,10016,2024-01-16,Books,"Salt, Fat, Acid, Heat by Samin Nosrat",3,35.99,107.97,North America,Credit Card
16,10017,2024-01-17,Beauty Products,Dyson Supersonic Hair Dryer,1,399.99,399.99,Europe,PayPal
17,10018,2024-01-18,Sports,Manduka PRO Yoga Mat,4,119.99,479.96,Asia,Credit Card
18,10019,2024-01-19,Electronics,Garmin Fenix 7,1,499.99,499.99,North America,Credit Card
19,10020,2024-01-20,Home Appliances,Ninja Professional Blender,1,99.99,99.99,Europe,PayPal

In [8]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count        20.00000   20.000000    20.000000       20.00000
mean      10010.50000    2.250000   379.890000      589.37750
std           5.91608    1.517442   568.939355      685.88568
min       10001.00000    1.000000    15.990000       25.99000
25%       10005.75000    1.000000    84.990000      124.48500
50%       10010.50000    2.000000   159.990000      439.97500
75%       10015.25000    3.000000   499.990000      554.94750
max       10020.00000    6.000000  2499.990000     2499.99000

In [9]:
df.dtypes

Transaction ID        int64
Date                    str
Product Category        str
Product Name            str
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region                  str
Payment Method          str
dtype: object

In [4]:
## Handling Missing Values
# Check for missing values in the dataset
df.isnull().any(axis=1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool

In [ ]:
# Count the number of missing values in each column
df.isnull().sum()

Transaction ID      0
Date                0
Product Category    0
Product Name        0
Units Sold          0
Unit Price          0
Total Revenue       0
Region              0
Payment Method      0
dtype: int64

In [12]:
### Filling missing values with the mean of the column
df['Total Revenue'].fillna(df['Total Revenue'].mean(), inplace=True)

C:\Users\tarun\AppData\Local\Temp\ipykernel_11704\492867435.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Total Revenue'].fillna(df['Total Revenue'].mean(), inplace=True)

0     1999.98
1      499.99
2      209.97
3       63.96
4       89.99
5      149.95
6     2499.99
7     1199.98
8      539.94
9       25.99
10     129.99
11     599.97
12    1499.98
13     189.99
14     499.98
15     107.97
16     399.99
17     479.96
18     499.99
19      99.99
Name: Total Revenue, dtype: float64

In [14]:
## Renaming Columns
df = df.rename(columns={'Total Revenue': 'Revenue', 'Units Sold': 'Units'})
df.head()

,Transaction ID,Date,Product Category,Product Name,Units,Unit Price,Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi’s 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [15]:
df['New Value'] = df['Revenue'].apply(lambda x : x*2)
df.head()

,Transaction ID,Date,Product Category,Product Name,Units,Unit Price,Revenue,Region,Payment Method,New Value
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,3999.96
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,999.98
2,10003,2024-01-03,Clothing,Levi’s 501 Jeans,3,69.99,209.97,Asia,Debit Card,419.94
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,127.92
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,179.98

In [17]:
grouped_mean = df.groupby('Product Category')['Revenue'].mean()
print(grouped_mean)

Product Category
Beauty Products     206.656667
Books                65.973333
Clothing            416.630000
Electronics        1624.985000
Home Appliances     497.487500
Sports              409.960000
Name: Revenue, dtype: float64

In [20]:
## Aggregate multiple nulriple funnctions
grouped_agg = df.groupby('Region')['Revenue'].agg(['mean', 'sum'])
grouped_agg

                     mean      sum
Region
Asia           568.535714  3979.75
Europe         403.321667  2419.93
North America  769.695714  5387.87

In [3]:
### Merging and joining Dataframes
df1 = pd.DataFrame({'key' : ['A', 'B', 'C'], 'value1' : [1, 2, 3]})
df2 = pd.DataFrame({'key' : ['A', 'B', 'D'], 'value2' : [4, 5, 6]})

In [4]:
df1

  key  value1
0   A       1
1   B       2
2   C       3

In [24]:
df2

  key  value2
0   A       4
1   B       5
2   D       6

In [5]:
## Merge the dataframe on the 'key' column
pd.merge(df1,df2, on = 'key', how = 'inner')

  key  value1  value2
0   A       1       4
1   B       2       5

In [8]:
pd.merge(df1,df2, on = 'key', how = 'outer')

  key  value1  value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [ ]:
pd.merge(df1,df2,on="key",how="left") #priority to df1

  key  value1  value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [9]:
pd.merge(df1,df2,on="key",how="right") #priority to df2

  key  value1  value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6