pandas is a powerful data manipilation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one - dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable.
Use:
Working with data (tables, Excel, CSV)
Data analysis and cleaning
Handling rows and columns

In [ ]:
import pandas as pd

In [3]:
## Series is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.). The axis labels are collectively referred to as the index.
data = [1, 2, 3, 4, 5]
s = pd.Series(data)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [12]:
## Create a series from Directionary
data = {'a': 1, 'b': 2, 'c': 3}
s = pd.Series(data)  
print(s)

a    1
b    2
c    3
dtype: int64

In [13]:
data = [10,20,30]
index = ['a', 'b', 'c'] 
s = pd.Series(data, index=index)
print(s)

a    10
b    20
c    30
dtype: int64

In [6]:
## DataFrame : A DataFrame is a two-dimensional labeled data structure with columns of potentially different types. It is similar to a spreadsheet or SQL table, and it is one of the most commonly used data structures in pandas.
## Create a Dataframe from a dictionary of list
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'City': ['New York', 'Los Angeles', 'Chicago']
        }
df = pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
<class 'pandas.core.frame.DataFrame'>

In [15]:
## Create a Data frame From a list of Dictionaries
data = [{'Name': 'Alice', 'Age': 25, 'City': 'New York'},
        {'Name': 'Bob', 'Age': 30, 'City': 'Los Angeles'},
        {'Name': 'Charlie', 'Age': 35, 'City': 'Chicago'}
        ]
df = pd.DataFrame(data)
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [16]:
df2 = pd.read_csv('sales_data.csv')
df2.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi’s 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [7]:
### Accessing Data From DataFrame
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [19]:
df['Name']

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str

In [20]:
print(df.at[1,'Age'])
df.at[2, 'Name']

30

'Charlie'

In [8]:
## Accessing a specified element using iat
df.iat[2,2]     #row index 2 and column index 2

'Chicago'

In [22]:
df['Salary'] = [50000, 60000, 70000]
df

      Name  Age         City  Salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000

In [23]:
 ## remove a column
df.drop('Salary', axis=1,inplace=True)

In [24]:
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [25]:
## add age to the colomn
df['Age'] = df['Age'] + 1
df

      Name  Age         City
0    Alice   26     New York
1      Bob   31  Los Angeles
2  Charlie   36      Chicago

In [26]:
df = pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi’s 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [28]:
#Display the data types of each column
print("Data types :\n", df.dtypes)

#Describe the dataframe
print("Dataframe description :\n", df.describe())

Data types :
 Transaction ID        int64
Date                    str
Product Category        str
Product Name            str
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region                  str
Payment Method          str
dtype: object
Dataframe description :
        Transaction ID  Units Sold   Unit Price  Total Revenue
count        20.00000   20.000000    20.000000       20.00000
mean      10010.50000    2.250000   379.890000      589.37750
std           5.91608    1.517442   568.939355      685.88568
min       10001.00000    1.000000    15.990000       25.99000
25%       10005.75000    1.000000    84.990000      124.48500
50%       10010.50000    2.000000   159.990000      439.97500
75%       10015.25000    3.000000   499.990000      554.94750
max       10020.00000    6.000000  2499.990000     2499.99000